# Generated by Django 3.0.3 on 2020-02-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail_text',
            field=models.TextField(default='degecgu', verbose_name='Details zur Frage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Frage'),
        ),
    ]
