# Generated by Django 3.0.3 on 2020-03-12 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Endzeitpunkt der Umfrage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Veröffentlichungszeitpunkt'),
        ),
    ]
