# Generated by Django 3.0.3 on 2020-03-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polls', '0005_auto_20200312_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.CharField(choices=[('apl', 'Aplerbeck'), ('bra', 'Brackel'), ('evi', 'Eving'), ('hom', 'Hombruch'), ('hoe', 'Hörde'), ('huc', 'Huckarde'), ('inn', 'Innenstadt-Nord'), ('ino', 'Innenstadt-Ost'), ('inw', 'Innenstadt-West'), ('lue', 'Lütgendortmund'), ('men', 'Mengede'), ('sch', 'Scharnhorst')], help_text='Optional.', max_length=10, verbose_name='Ihr Bezirk')),
            ],
        ),
    ]
