# Generated by Django 3.0.3 on 2020-03-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Stadtbezirk')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='neighborhood',
            field=models.ManyToManyField(to='polls.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighborhood'),
        ),
    ]
