# Generated by Django 3.0.3 on 2020-03-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200317_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='neighborhood',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='categories',
        ),
    ]
