# Generated by Django 3.0.4 on 2020-03-31 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20200317_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_voted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
