# Generated by Django 3.0.4 on 2020-03-31 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_question_has_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='has_voted',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
